### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#815]
### 1. Mod compatibility and duplicated mods buttons
The mod compatibility and duplicated mods buttons at the top of the mod list are not spaced.
Also, the red color of the duplicated mods button hurts my eyes.
I edited the CSS like this:
```css
.v-application .error {
    background-color: rgba(255, 82, 82, 0.5) !important; /* ◀ I darkened the color by making it less opaque, but I kept the original #ff5252 color */
    border-color: rgba(255, 82, 82, 0.5) !important;
}
.v-application .info {
    background-color: rgba(33, 150, 243, 0.5) !important; /* ◀ Same here */
    border-color: rgba(33, 150, 243, 0.5) !important;
}

.v-sheet.v-alert {
    border-radius: 4px; /* (Already in the code) */
    margin: 0px 8px 8px 8px !important; /* ◀ Increased the bottom, right and left margins */
}
```
And it looks like this:
![image](https://github.com/user-attachments/assets/875eac7a-6a8f-4dd2-ad90-2855891d9986)

### 2. Duplicated mods alert on instance page
The duplicated mods alert visible on the instance page hurts my eyes and hides the enabled mod count.
A better way to warn the user of duplicated mods should be something less invasive, like a button. The button could open the dialog asking which mods to keep.
I edited the UI like this:
```html
<div>  <!--(Normal "Mods" card)-->
    <!--(Title)-->
    <div data-v-4aace79a="" class="v-card__text flex-grow relative">
        6 mods enabled <!-- ◀ Keep the enabled mods count visible-->
        <div data-v-4aace79a="" class="mt-4">
            <!--(Mods icons)-->
        </div>
    </div>
    <div data-v-4aace79a="" class="v-card__actions">
        <!--("Manage mods" button)-->
        <!--▼ New "duplicated mods" button ▼-->
        <button data-v-4aace79a="" type="button" class="v-btn v-btn--text theme--dark v-size--default teal--text text--accent-4"
            style="color: #f44336 !important;"> <!--I used the style property to make it red-->
            <span class="v-btn__content">
                <i data-v-4aace79a="" aria-hidden="true" class="v-icon notranslate v-icon--left material-icons theme--dark">warning</i>  <!--Warning icon-->
                1 duplicated mod
            </span>
        </button>
    </div>
</div>
```
I removed some of the code to make the snippet more readable and replaced it by placeholders like `<!--(Mods icons)-->`
It looks like this:
![image](https://github.com/user-attachments/assets/352f71e2-1253-4bd8-aa0a-5fe5ce07a2f1)
